// Code generated by qtc from "layout.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/layout.qtpl:1
package templates

//line templates/layout.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/layout.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/layout.qtpl:1
func StreamLayout(qw422016 *qt422016.Writer, title string, contents string) {
//line templates/layout.qtpl:1
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>PaaS Mark - `)
//line templates/layout.qtpl:7
	qw422016.E().S(title)
//line templates/layout.qtpl:7
	qw422016.N().S(`</title>
  <link href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css" rel="stylesheet">
  <style>
    .navbar { margin-bottom: 1.5rem; }
    .result-box { margin-top: 2rem; }
    .stat-value { font-size: 2rem; font-weight: bold; }
    .stat-label { font-size: 0.9rem; color: #666; }
    .error-list { max-height: 200px; overflow-y: auto; }
  </style>
</head>
<body>
  <nav class="navbar is-dark" role="navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="/">
        <strong>PaaS Mark</strong>
      </a>
    </div>
    <div class="navbar-menu">
      <div class="navbar-start">
        <span class="navbar-item">Hosting Benchmark</span>
      </div>
    </div>
  </nav>

  <section class="section">
    <div class="container">
      `)
//line templates/layout.qtpl:33
	qw422016.N().S(contents)
//line templates/layout.qtpl:33
	qw422016.N().S(`
    </div>
  </section>
</body>
</html>
`)
//line templates/layout.qtpl:38
}

//line templates/layout.qtpl:38
func WriteLayout(qq422016 qtio422016.Writer, title string, contents string) {
//line templates/layout.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/layout.qtpl:38
	StreamLayout(qw422016, title, contents)
//line templates/layout.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line templates/layout.qtpl:38
}

//line templates/layout.qtpl:38
func Layout(title string, contents string) string {
//line templates/layout.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/layout.qtpl:38
	WriteLayout(qb422016, title, contents)
//line templates/layout.qtpl:38
	qs422016 := string(qb422016.B)
//line templates/layout.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/layout.qtpl:38
	return qs422016
//line templates/layout.qtpl:38
}
